"""Generate the profile README's SVG assets.

Text is outlined from IBM Plex Mono (SIL OFL 1.1) so every image renders the
same everywhere. Palette, type and window chrome follow DESIGN.md and
assets/profile-header.svg.

    python3 -m venv .venv && .venv/bin/pip install fonttools
    .venv/bin/python scripts/build_assets.py

Fonts are downloaded once into scripts/.fonts/ (git-ignored).
"""

from __future__ import annotations

import pathlib
import urllib.request

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
FONT_DIR = pathlib.Path(__file__).resolve().parent / ".fonts"
FONT_URL = "https://github.com/google/fonts/raw/main/ofl/ibmplexmono/IBMPlexMono-{}.ttf"

DESKTOP = 760
PHONE = 400

# Color tokens (DESIGN.md).
BG = "#0A0A0B"
PANEL = "#111113"
BORDER = "#262628"
RULE = "#242426"
TEXT = "#F2F0EB"
SOFT = "#B8B6B1"
MUTED = "#8A8A8A"
DIM = "#4A4946"
DIMMER = "#2D2D2F"
ACCENT = "#C9BFA8"
LIVE = "#8FBF8F"
BUILD = "#D9A65B"

LIGHT_LABEL = "#57534C"
LIGHT_ACCENT = "#6F6450"
LIGHT_RULE = "#DAD5C9"
DARK_RULE = "#2A2A2C"

# Animations. Each one decorates a frame that is already complete, so a
# renderer that freezes on any frame (or ignores CSS) still shows the whole
# graphic. ALT_FRAME_CSS pins every animated class to its other extreme for
# scripts/preview.py.
MOTION_CSS = (
    "@keyframes blink{0%,49%{opacity:1}50%,100%{opacity:0}}"
    ".cursor{animation:blink 1.1s infinite}"
    "@keyframes ring{0%{opacity:.7;transform:scale(1)}70%,100%{opacity:0;transform:scale(2.8)}}"
    ".ring{transform-box:fill-box;transform-origin:center;animation:ring 2.4s ease-out infinite}"
    "@keyframes step{0%,100%{opacity:0}3%,17%{opacity:1}21%{opacity:0}}"
    ".hl{animation:step 6s ease-in-out infinite}"
    "@media (prefers-reduced-motion:reduce){.cursor,.ring,.hl{animation:none}}"
)
ALT_FRAME_CSS = ".cursor{opacity:0!important}.ring{opacity:.7!important}.hl{opacity:1!important}"

_fonts: dict[str, TTFont] = {}


def font(weight: str) -> TTFont:
    if weight not in _fonts:
        path = FONT_DIR / f"IBMPlexMono-{weight}.ttf"
        if not path.exists():
            FONT_DIR.mkdir(exist_ok=True)
            urllib.request.urlretrieve(FONT_URL.format(weight), path)
        _fonts[weight] = TTFont(path)
    return _fonts[weight]


def text_width(s: str, size: float, weight: str = "Regular", spacing: float = 0) -> float:
    f = font(weight)
    cmap = f.getBestCmap()
    total = sum(f["hmtx"][cmap[ord(ch)]][0] for ch in s) * size / f["head"].unitsPerEm
    return total + spacing * (len(s) - 1)


def text(s: str, x: float, y: float, size: float, fill: str, weight: str = "Regular",
         spacing: float = 0, anchor: str = "start") -> str:
    """Outline `s` as a single <path>, with (x, y) at the baseline."""
    f = font(weight)
    cmap = f.getBestCmap()
    glyphs = f.getGlyphSet()
    scale = size / f["head"].unitsPerEm
    if anchor == "end":
        x -= text_width(s, size, weight, spacing)
    elif anchor == "middle":
        x -= text_width(s, size, weight, spacing) / 2
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.1f}".rstrip("0").rstrip("."))
    cursor = x
    for ch in s:
        if ord(ch) not in cmap:
            raise ValueError(f"IBM Plex Mono has no glyph for {ch!r}")
        name = cmap[ord(ch)]
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, cursor, y)))
        cursor += f["hmtx"][name][0] * scale + spacing
    return f'<path fill="{fill}" d="{pen.getCommands()}"/>'


def wrap(words: list[str], size: float, width: float, sep: str) -> list[list[str]]:
    """Greedy line-wrap of `words` joined by `sep` into lines no wider than `width`."""
    lines: list[list[str]] = [[]]
    for w in words:
        trial = sep.join(lines[-1] + [w])
        if lines[-1] and text_width(trial, size) > width:
            lines.append([w])
        else:
            lines[-1].append(w)
    return lines


def svg(width: float, height: float, title: str, desc: str, body: list[str], animated: bool = False) -> str:
    style = f"\n  <style>{MOTION_CSS}</style>" if animated else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title description">\n'
        f'  <title id="title">{title}</title>\n'
        f'  <desc id="description">{desc}</desc>\n'
        f"  <!-- Generated by scripts/build_assets.py. Text is outlined from IBM Plex Mono (SIL OFL 1.1). -->"
        f"{style}\n  " + "\n  ".join(body) + "\n</svg>\n"
    )


def window(width: float, height: float, caption: str, cursor: bool = False) -> list[str]:
    """Dark terminal window chrome, matching the header."""
    cap = 12 if width == DESKTOP else 13
    parts = [
        f'<rect width="{width}" height="{height}" rx="18" fill="{BG}"/>',
        f'<rect x="0.75" y="0.75" width="{width - 1.5}" height="{height - 1.5}" rx="17.25" '
        f'fill="none" stroke="{BORDER}" stroke-width="1.5"/>',
        f'<circle cx="30" cy="28" r="4" fill="{ACCENT}" opacity="0.9"/>'
        f'<circle cx="46" cy="28" r="4" fill="{DIM}"/><circle cx="62" cy="28" r="4" fill="{DIMMER}"/>',
        text(caption, 86.5, 33, cap, MUTED),
        f'<line x1="24" y1="52" x2="{width - 24}" y2="52" stroke="{RULE}"/>',
    ]
    if cursor:
        cx = 86.5 + text_width(caption, cap) + 5
        parts.append(f'<rect class="cursor" x="{cx:.1f}" y="23.5" width="7" height="12" fill="{ACCENT}"/>')
    return parts


def status_dot(cx: float, cy: float, color: str, pulse: bool) -> list[str]:
    out = [f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="4" fill="{color}"/>']
    if pulse:
        out.append(f'<circle class="ring" cx="{cx:.1f}" cy="{cy:.1f}" r="4" fill="none" '
                   f'stroke="{color}" stroke-width="1.5" opacity="0"/>')
    return out


def write(name: str, content: str) -> None:
    (ASSETS / name).write_text(content)
    print(f"wrote assets/{name} ({len(content) / 1024:.1f} KB)")


# --- Header (phone) ----------------------------------------------------------
# The desktop header is the hand-tuned assets/profile-header.svg; this is its
# stacked layout for narrow screens, with the same content.

HEADER_BUILDING = ["Ledger.m", "EasyMail", "Stay Tuned"]


def monogram(x: float, y: float, s: float) -> list[str]:
    """The header's MM monogram, with its top-left (47, 115) moved to (x, y) at scale s."""
    m = "M55 229 L55 139 L92.5 206 L130 139 L167.5 206 L205 139 L205 229 M130 139 V229"
    return [
        f'<g transform="translate({x - 47 * s:.2f} {y - 115 * s:.2f}) scale({s})">',
        '<clipPath id="mmclip"><rect x="40" y="139" width="180" height="90"/></clipPath>',
        f'<g fill="none" stroke-linejoin="miter" stroke-miterlimit="10" clip-path="url(#mmclip)">'
        f'<path d="{m}" stroke="{ACCENT}" stroke-width="7"/><path d="{m}" stroke="{BG}" stroke-width="4"/></g>',
        f'<g fill="none" stroke="{ACCENT}" stroke-width="1.5"><path d="M47 128 H213 M47 240 H213" '
        f'opacity="0.55" stroke-width="1"/><path d="M130 115 l5 5 -5 5 -5 -5 Z"/></g>',
        "</g>",
    ]


def header_phone() -> str:
    w, h = PHONE, 452
    body = window(w, h, "meron@matti:~", cursor=True)
    body.append(text("IDENTITY // 01", 30, 86, 13, MUTED, "Bold", 2))
    body += monogram(30, 106, 0.6)
    body += [
        text("Meron Matti", 150, 138, 24, TEXT, "Bold"),
        text("Full-Stack /", 150, 164, 14, ACCENT, "Medium"),
        text("Indie Developer", 150, 184, 14, ACCENT, "Medium"),
        f'<line x1="24" y1="206" x2="{w - 24}" y2="206" stroke="{RULE}"/>',
        text("BUILDING", 30, 234, 13, MUTED, "Bold", 2),
    ]
    for i, item in enumerate(HEADER_BUILDING):
        branch = "└── " if i == len(HEADER_BUILDING) - 1 else "├── "
        body.append(text(branch + item, 30, 262 + i * 26, 15, TEXT if i == 0 else SOFT))
    body += [
        f'<line x1="24" y1="344" x2="{w - 24}" y2="344" stroke="{RULE}"/>',
        text("CONTEXT", 30, 372, 13, MUTED, "Bold", 2),
        text("Oakland University", 30, 398, 14, TEXT),
        text("B.S. Computer Science · May 2027", 30, 420, 14, TEXT),
        text("Michigan, USA", 30, 440, 14, MUTED),
    ]
    return svg(w, h, "Meron Matti — Full-Stack / Indie Developer",
               "Terminal-style profile card with an MM monogram. Meron Matti, Full-Stack / Indie Developer. "
               f"Building: {', '.join(HEADER_BUILDING)}. Oakland University, B.S. Computer Science, May 2027, "
               "Michigan, USA.", body, animated=True)


# --- Section headings --------------------------------------------------------

SECTIONS = {
    "index": ("02", "INDEX"),
    "work": ("03", "SELECTED WORK"),
    "toolkit": ("04", "TOOLKIT"),
    "progress": ("05", "IN PROGRESS"),
    "contact": ("06", "CONTACT"),
}


def section(number: str, label: str, dark: bool, width: float) -> str:
    size = 13 if width == DESKTOP else 15
    label_fill = MUTED if dark else LIGHT_LABEL
    accent = ACCENT if dark else LIGHT_ACCENT
    left = f"{label} // "
    lw = text_width(left, size, "Bold", 2.4)
    rule_x = lw + text_width(number, size, "Bold", 2.4) + 18
    body = [
        text(left, 0, 26, size, label_fill, "Bold", 2.4),
        text(number, lw, 26, size, accent, "Bold", 2.4),
        f'<line x1="{rule_x:.1f}" y1="20.5" x2="{width - 18}" y2="20.5" stroke="{DARK_RULE if dark else LIGHT_RULE}"/>',
        f'<path d="M{width - 7} 15.5 l5 5 -5 5 -5 -5 Z" fill="none" stroke="{accent}" stroke-width="1.5"/>',
    ]
    return svg(width, 40, label.title(), f"Section heading: {label.title()}.", body)


# --- Project index -----------------------------------------------------------

# (status label, dot color, pulses, name, desktop description, phone description)
PROJECTS = [
    ("PRIVATE", MUTED, False, "Ledger.m",
     "personal finance, connected to my bank through Plaid", "personal finance, synced through Plaid"),
    ("LIVE", LIVE, True, "Dummy Peptides",
     "storefront for a research-peptide business I co-own", "store for a peptide business I co-own"),
    ("DEMO", MUTED, False, "Imperium",
     "agent that runs my Mac from my phone", "agent that runs my Mac from my phone"),
    ("SOURCE", MUTED, False, "Cosmo",
     "iOS astrology app with AI readings + subscriptions", "iOS astrology app with AI readings"),
    ("BETA", BUILD, False, "StayDue",
     "syllabus PDF in, every deadline in one calendar", "syllabus PDF in, deadlines out"),
    ("BUILDING", BUILD, False, "EasyMail",
     "recap-first triage across Gmail and Outlook", "recap-first triage, Gmail + Outlook"),
]


def index_desc() -> str:
    return "Project list. " + " ".join(f"{name}: {long} ({status.lower()})." for status, _, _, name, long, _ in PROJECTS)


def index_desktop() -> str:
    w = DESKTOP
    first, row_h = 128, 34
    h = first + row_h * (len(PROJECTS) - 1) + 30
    body = window(w, h, "meron@matti:~/projects")
    body += [text("$", 30, 88, 14, ACCENT, "SemiBold"), text("ls ~/projects", 48, 88, 14, TEXT)]
    for i, (status, color, pulse, name, desc, _) in enumerate(PROJECTS):
        y = first + i * row_h
        body += status_dot(36, y - 4.5, color, pulse)
        body += [
            text(status, 50, y, 11, MUTED, "Bold", 1.6),
            text(name, 150, y, 14, TEXT, "SemiBold"),
            text(desc, 290, y, 12.5, SOFT),
        ]
        if 290 + text_width(desc, 12.5) > w - 30:
            raise ValueError(f"index row {name!r} overflows")
        if i < len(PROJECTS) - 1:
            body.append(f'<line x1="30" y1="{y + 14}" x2="{w - 30}" y2="{y + 14}" stroke="#18181A"/>')
    return svg(w, h, "Projects", index_desc(), body, animated=True)


def index_phone() -> str:
    w = PHONE
    first, row_h = 128, 56
    h = first + row_h * (len(PROJECTS) - 1) + 44
    body = window(w, h, "~/projects")
    body += [text("$", 30, 88, 15, ACCENT, "SemiBold"), text("ls ~/projects", 50, 88, 15, TEXT)]
    for i, (status, color, pulse, name, _, short) in enumerate(PROJECTS):
        y = first + i * row_h
        body += status_dot(36, y - 5, color, pulse)
        body += [
            text(name, 50, y, 15, TEXT, "SemiBold"),
            text(status, w - 30, y - 1, 13, MUTED, "Bold", 1.6, anchor="end"),
            text(short, 50, y + 22, 13, SOFT),
        ]
        if 50 + text_width(short, 13) > w - 24:
            raise ValueError(f"phone index row {name!r} overflows")
        if i < len(PROJECTS) - 1:
            body.append(f'<line x1="30" y1="{y + 36}" x2="{w - 30}" y2="{y + 36}" stroke="#18181A"/>')
    return svg(w, h, "Projects", index_desc(), body, animated=True)


# --- Imperium pipeline -------------------------------------------------------

STAGES = [
    ("01", "PAIR", "token-paired,", "deny by default"),
    ("02", "PLAN", "Claude turns", "text into steps"),
    ("03", "PERMIT", "risky actions", "need a tap"),
    ("04", "GATE", "scripts lexed,", "policy-checked"),
    ("05", "RUN", "AppleScript +", "app integrations"),
]
IMPERIUM_DESC = (
    "Diagram of how Imperium handles a command such as 'Play Drake on Spotify' sent from a phone: "
    "01 pair (token-paired auth, deny by default), 02 plan (Claude turns text into steps), "
    "03 permit (risky actions need a confirm tap), 04 gate (scripts are lexed and policy-checked), "
    "05 run (AppleScript and app integrations). Every stage writes to an append-only audit log."
)


def highlight(x: float, y: float, w: float, h: float, i: int) -> str:
    return (f'<rect class="hl" style="animation-delay:{i * 1.2:.1f}s" x="{x:.1f}" y="{y}" width="{w:.1f}" '
            f'height="{h}" rx="10" fill="none" stroke="{ACCENT}" stroke-width="1.5" opacity="0"/>')


def imperium_desktop() -> str:
    w, h = DESKTOP, 318
    body = window(w, h, "imperium — what happens to one command")
    body += [
        text(">", 30, 92, 15, ACCENT, "SemiBold"),
        text('"Play Drake on Spotify"', 50, 92, 15, TEXT),
        text("PHONE → MAC", w - 30, 91, 11, MUTED, "Bold", 2, anchor="end"),
    ]
    x0, gap, top, box_h, audit_y = 24, 14, 118, 104, 250
    box_w = (w - 2 * x0 - gap * (len(STAGES) - 1)) / len(STAGES)
    dots = []
    for i, (num, name, l1, l2) in enumerate(STAGES):
        x = x0 + i * (box_w + gap)
        cx = x + box_w / 2
        body += [
            f'<rect x="{x:.1f}" y="{top}" width="{box_w:.1f}" height="{box_h}" rx="10" fill="{PANEL}" stroke="{BORDER}"/>',
            highlight(x, top, box_w, box_h, i),
            text(num, x + 14, top + 24, 11, ACCENT, "Bold", 1.5),
            text(name, x + 14, top + 47, 15, TEXT, "SemiBold", 1),
            text(l1, x + 14, top + 70, 11.5, MUTED),
            text(l2, x + 14, top + 86, 11.5, MUTED),
            f'<line x1="{cx:.1f}" y1="{top + box_h}" x2="{cx:.1f}" y2="{audit_y}" stroke="{DIM}" stroke-dasharray="2 4"/>',
        ]
        dots.append(f'<circle cx="{cx:.1f}" cy="{audit_y}" r="2.5" fill="{ACCENT}"/>')
        if x + 14 + text_width(max(l1, l2, key=len), 11.5) > x + box_w - 6:
            raise ValueError(f"stage {name} caption overflows")
        if i < len(STAGES) - 1:
            ax, ay = x + box_w + gap / 2, top + box_h / 2
            body.append(f'<path d="M{ax - 3:.1f} {ay - 4} l4 4 -4 4" fill="none" stroke="{ACCENT}" '
                        f'stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>')
    body += [
        f'<rect x="{x0}" y="{audit_y}" width="{w - 2 * x0}" height="44" rx="10" fill="{PANEL}" stroke="{BORDER}"/>',
        text("AUDIT LOG", x0 + 14, audit_y + 27, 11, ACCENT, "Bold", 2),
        text("append-only record of every command, decision, and script", x0 + 124, audit_y + 27, 12, SOFT),
        *dots,
    ]
    return svg(w, h, "Imperium request pipeline", IMPERIUM_DESC, body, animated=True)


def imperium_phone() -> str:
    w = PHONE
    top, box_h, gap = 112, 58, 12
    box_x, box_w, rail = 24, 318, 364
    audit_y = top + len(STAGES) * (box_h + gap) + 6
    h = audit_y + 88
    body = window(w, h, "imperium")
    body += [text(">", 30, 88, 15, ACCENT, "SemiBold"), text('"Play Drake on Spotify"', 50, 88, 15, TEXT)]
    first_mid = top + box_h / 2
    body.append(f'<line x1="{rail}" y1="{first_mid}" x2="{rail}" y2="{audit_y}" stroke="{DIM}" stroke-dasharray="2 4"/>')
    for i, (num, name, l1, l2) in enumerate(STAGES):
        y = top + i * (box_h + gap)
        mid = y + box_h / 2
        body += [
            f'<rect x="{box_x}" y="{y}" width="{box_w}" height="{box_h}" rx="10" fill="{PANEL}" stroke="{BORDER}"/>',
            highlight(box_x, y, box_w, box_h, i),
            text(num, box_x + 14, y + 24, 13, ACCENT, "Bold", 1.5),
            text(name, box_x + 50, y + 24, 15, TEXT, "SemiBold", 1),
            text(f"{l1} {l2}", box_x + 14, y + 45, 13, MUTED),
            f'<line x1="{box_x + box_w}" y1="{mid}" x2="{rail}" y2="{mid}" stroke="{DIM}" stroke-dasharray="2 4"/>',
            f'<circle cx="{rail}" cy="{mid}" r="2.5" fill="{ACCENT}"/>',
        ]
        if box_x + 14 + text_width(f"{l1} {l2}", 13) > box_x + box_w - 10:
            raise ValueError(f"phone stage {name} caption overflows")
    body += [
        f'<rect x="{box_x}" y="{audit_y}" width="{w - 2 * box_x}" height="64" rx="10" fill="{PANEL}" stroke="{BORDER}"/>',
        f'<circle cx="{rail}" cy="{audit_y}" r="2.5" fill="{ACCENT}"/>',
        text("AUDIT LOG", box_x + 14, audit_y + 26, 13, ACCENT, "Bold", 2),
        text("every command, decision, and script", box_x + 14, audit_y + 48, 13, SOFT),
    ]
    return svg(w, h, "Imperium request pipeline", IMPERIUM_DESC, body, animated=True)


# --- Toolkit -----------------------------------------------------------------

TOOLKIT = [
    ("LANGUAGES", ["TypeScript", "Python", "Java", "SQL"]),
    ("FRONTEND", ["React", "Next.js", "React Native", "Expo", "Tailwind CSS"]),
    ("BACKEND", ["Supabase", "Postgres", "FastAPI", "Node.js"]),
    ("AI", ["Anthropic API", "OpenAI API", "agents", "structured extraction"]),
    ("INTEGRATIONS", ["Plaid", "RevenueCat", "Shippo", "Resend", "Twilio", "Google Maps"]),
    ("SHIPPING", ["Vercel", "Docker", "Vitest", "Playwright", "Git"]),
]
TOOLKIT_DESC = "; ".join(f"{k.title()}: {', '.join(v)}" for k, v in TOOLKIT) + "."
SEP = " · "


def tool_line(items: list[str], x: float, y: float, size: float, lead: bool) -> tuple[list[str], float]:
    out = []
    for j, item in enumerate(items):
        if j:
            out.append(text(SEP, x, y, size, DIM))
            x += text_width(SEP, size)
        out.append(text(item, x, y, size, TEXT if lead and j == 0 else SOFT))
        x += text_width(item, size)
    return out, x


def toolkit_desktop() -> str:
    w, row_h, first = DESKTOP, 36, 92
    h = first + row_h * (len(TOOLKIT) - 1) + 34
    body = window(w, h, "meron@matti:~/toolkit")
    for i, (key, items) in enumerate(TOOLKIT):
        y = first + i * row_h
        body.append(text(key, 30, y, 11, MUTED, "Bold", 2))
        parts, end = tool_line(items, 178, y, 13.5, lead=True)
        body += parts
        if end > w - 30:
            raise ValueError(f"toolkit row {key!r} overflows")
        if i < len(TOOLKIT) - 1:
            body.append(f'<line x1="30" y1="{y + 14}" x2="{w - 30}" y2="{y + 14}" stroke="#18181A"/>')
    return svg(w, h, "Toolkit", TOOLKIT_DESC, body)


def toolkit_phone() -> str:
    w, size, line_h = PHONE, 14, 22
    body: list[str] = []
    y = 86
    for i, (key, items) in enumerate(TOOLKIT):
        body.append(text(key, 30, y, 13, MUTED, "Bold", 2))
        for k, line in enumerate(wrap(items, size, w - 60, SEP)):
            y += line_h
            parts, _ = tool_line(line, 30, y, size, lead=k == 0)
            body += parts
        if i < len(TOOLKIT) - 1:
            body.append(f'<line x1="30" y1="{y + 14}" x2="{w - 30}" y2="{y + 14}" stroke="#18181A"/>')
            y += 40
    h = y + 26
    return svg(w, h, "Toolkit", TOOLKIT_DESC, window(w, h, "~/toolkit") + body)


# --- Contact buttons and footer ---------------------------------------------

def button(label: str) -> str:
    bw, bh = 164, 46
    tw = text_width(label, 12, "Bold", 2.4)
    ax = bw / 2 - 8 + tw / 2 + 10  # 10px after the label
    body = [
        f'<rect x="0.75" y="0.75" width="{bw - 1.5}" height="{bh - 1.5}" rx="11" fill="{BG}" stroke="{BORDER}" stroke-width="1.5"/>',
        text(label, bw / 2 - 8, 28.5, 12, ACCENT, "Bold", 2.4, anchor="middle"),
        f'<path d="M{ax:.1f} 27.5 l7 -7 M{ax + 2:.1f} 20.5 h5 v5" fill="none" stroke="{ACCENT}" '
        f'stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
    ]
    return svg(bw, bh, label.title(), f"{label.title()} link button.", body)


def footer(width: float) -> str:
    size = 14 if width == DESKTOP else 15
    h = 150
    body = window(width, h, "meron@matti:~")
    body += [
        text("$", 30, 88, size, ACCENT, "SemiBold"),
        text('echo "thanks for stopping by"', 48, 88, size, TEXT),
        text("thanks for stopping by", 30, 112, size, MUTED),
        text("$", 30, 136, size, ACCENT, "SemiBold"),
        f'<rect class="cursor" x="48" y="123" width="{size * 0.6:.1f}" height="{size + 1}" fill="{ACCENT}"/>',
    ]
    return svg(width, h, "Thanks for stopping by",
               'Terminal line: echo "thanks for stopping by", followed by a blinking cursor.', body, animated=True)


def main() -> None:
    write("header-phone.svg", header_phone())
    for key, (number, label) in SECTIONS.items():
        for theme, dark in (("dark", True), ("light", False)):
            write(f"section-{key}-{theme}.svg", section(number, label, dark, DESKTOP))
            write(f"section-{key}-{theme}-phone.svg", section(number, label, dark, PHONE))
    write("index.svg", index_desktop())
    write("index-phone.svg", index_phone())
    write("imperium-pipeline.svg", imperium_desktop())
    write("imperium-pipeline-phone.svg", imperium_phone())
    write("toolkit.svg", toolkit_desktop())
    write("toolkit-phone.svg", toolkit_phone())
    write("button-linkedin.svg", button("LINKEDIN"))
    write("button-email.svg", button("EMAIL"))
    write("footer.svg", footer(DESKTOP))
    write("footer-phone.svg", footer(PHONE))


if __name__ == "__main__":
    main()
